<?php
return array(
    'group_all'=>array(
        'name'=>'超级管理员',
        'permission'=>array(
	        'system'=>array(),
            'forum'=>array(),
            'game'=>array(),
            'user'=>array(),
			'activity'=>array(),
            'comment'=>array(),
    		'shop'=>array(),
			'giftbag'=>array(),
			'message'=>array(),
			'feedback'=>array(),
			'adv'=>array(),
        ),
        'menu'=>array(
            'system'=>array('name'=>'系统','url'=>'system/setting/index','child_menu'=>array(
                'setting'=>array('name'=>'网站设置','url'=>'system/setting/index'),
                'version'=>array('name'=>'版本管理','url'=>'system/setting/app-version-list'),
                'credit'=>array('name'=>'积分设置','url'=>'system/credit'),                
                'grade'=>array('name'=>'积分等级','url'=>'system/grade/index'),
                'notice'=>array('name'=>'通知设置','url'=>'system/notice/index'),
                'task-index'=>array('name'=>'任务管理','url'=>'system/task/index'),
                'task-checkin'=>array('name'=>'签到设置','url'=>'system/task/checkin'),
        		'task-tuiguang'=>array('name'=>'推广设置','url'=>'system/task/tuiguang'),
                'checkintest'=>array('name'=>'签到测试','url'=>'system/task/edit-checkin'),
                'picture'=>array('name'=>'首页图片设置','url'=>'system/picture/config'),
                //'api-profile'=>array('name'=>'API统计','url'=>'system/profile/index'),
                //'cache'=>array('name'=>'缓存管理','url'=>'system/setting/cache'),
		        //'client'=>array('name'=>'客户端管理','url'=>'system/client-list'),
// 		        'privilege'=>array('name'=>'权限管理','url'=>'system/privilege'),
            	'adminlist' =>array ('name' => '管理员列表', 'url' =>'system/admin' ),
            	'permission'=>array('name'=>'权限设置','url'=>'system/permission'),
            	'group'=>array('name'=>'权限组','url'=>'system/group'),
            	'operatelog' =>array ('name' => '操作记录', 'url' =>'system/operate' )
                )
            ),
            'game'=>array('name'=>'游戏库','url'=>'game/games/search','child_menu'=>array(
                'games'=>array('name'=>'游戏管理','url'=>'game/games/search'),
            	'game-add'=>array('name'=>'游戏添加','url'=>'game/games/game-add'),
                //'gametype'=>array('name'=>'游戏分类','url'=>'game/gametype/list'),
                )            
            ),
            'forum'=>array('name'=>'微论坛','url'=>'forum/topic/search','child_menu'=>array(                
                'topic'=>array('name'=>'帖子管理','url'=>'forum/topic/search'),
                'topic_create'=>array('name'=>'发新帖','url'=>'forum/topic/add'),
                //'forum'=>array('name'=>'论坛管理','url'=>'forum/channel/list'),
                'notice'=>array('name'=>'公告管理','url'=>'forum/notice/list'),
                'inform'=>array('name'=>'举报管理','url'=>'forum/inform/list'),
                'forum'=>array('name'=>'已开放论坛','url'=>'forum/game/search'),
                'expedition-list'=>array('name'=>'新游远征队','url'=>'forum/channel/expedition-list'),
                'expendition'=>array('name'=>'3.1版新游远征队','url'=>'forum/channel/list?game_id=2'),
                'credit-rule'=>array('name'=>'积分规则','url'=>'forum/topic/rule'),                
                )
            ),           
            'user'=>array('name'=>'用户','url'=>'user/users/index','child_menu'=>array(
                'users'=>array('name'=>'用户管理','url'=>'user/users/index'),
                'users-create'=>array('name'=>'创建用户','url'=>'user/users/create'),
            	'batch-credit'=>array('name'=>'批量发游币','url'=>'user/users/batch-send')
                //'usergroup'=>array('name'=>'用户组管理','url'=>'user/group-list'),
                )
            ),
            'comment'=>array('name'=>'评论','url'=>'comment/comments/index','child_menu'=>array(
                'list'=>array('name'=>'评论管理','url'=>'comment/comments/index'), 
                'inform'=>array('name'=>'举报管理','url'=>'comment/inform/list'),               
                )            
            ), 

            'activity'=>array('name'=>'活动','url'=>'activity/hunt/list','child_menu'=>array(
                'hunt-list'=>array('name'=>'寻宝箱活动','url'=>'activity/hunt/list'),
                'hunt-add'=>array('name'=>'添加宝箱','url'=>'activity/hunt/add'),
                'event-list'=>array('name'=>'有奖问答活动','url'=>'activity/event/list/1'),
                'event-add'=>array('name'=>'添加有奖问答','url'=>'activity/event/add/1'),
                'topic-list'=>array('name'=>'论坛活动','url'=>'activity/event/list/2'),
                'topic-add'=>array('name'=>'添加论坛活动','url'=>'activity/event/add/2'),
                'prize-list'=>array('name'=>'奖品管理','url'=>'activity/prize/home'),
                )            
            ),
            
            'shop'=>array('name'=>'商城','url'=>'shop/goods/list','child_menu'=>array(
                'goods-list'=>array('name'=>'商品管理','url'=>'shop/goods/list'),
                'goods-cate'=>array('name'=>'分类管理','url'=>'shop/goods/cate-list'),
                'goods-add'=>array('name'=>'添加商品','url'=>'shop/goods/add'),
                'exchange'=>array('name'=>'兑换管理','url'=>'shop/exchange/list'),
                'wish'=>array('name'=>'许愿帖','url'=>'shop/goods/rule'),
                )            
            ),            
            'giftbag'=>array('name'=>'礼包','url'=>'giftbag/gift/search','child_menu'=>array(
                'gift_search'=>array('name'=>'礼包列表','url'=>'giftbag/gift/search'),
                'gift_add'=>array('name'=>'添加礼包','url'=>'giftbag/gift/add'),
                )
            ),   
            'message'=>array('name'=>'消息推送','url'=>'message/push/list','child_menu'=>array(
                'push-list'=>array('name'=>'推送列表','url'=>'message/push/list'),
                'tpl-list'=>array('name'=>'通知模板','url'=>'message/tpl/list'),
                )            
            ),
            'feedback'=>array('name'=>'用户反馈','url'=>'feedback/chat/users','child_menu'=>array(
                'user-list'=>array('name'=>'反馈列表','url'=>'feedback/chat/users'),
                )            
            ),
            'adv'=>array('name'=>'广告','url'=>'adv/home/index','child_menu'=>array(
                //'home'=>array('name'=>'广告','url'=>'adv/home/index'),
                'credit'=>array('name'=>'游戏下载游币奖励','url'=>'adv/credit/index'),
                'adv-homepage-shuffles'=>array('name'=>'首页轮播广告','url'=>'adv/ads/list/1'),                
                'adv-homepage-homebar'=>array('name'=>'首页广告条','url'=>'adv/ads/list/8'),
                'adv-homepage-pop'=>array('name'=>'首页弹窗广告','url'=>'adv/ads/list/6'),
                'adv-hotgame'=>array('name'=>'热门游戏推荐','url'=>'adv/ads/list/2'),
                'adv-gamedetailpage-pop'=>array('name'=>'游戏详情页弹窗广告','url'=>'adv/ads/list/3'),
                'adv-gamedetailpage-btn'=>array('name'=>'游戏详情页下载按钮广告','url'=>'adv/ads/list/4'),
                //'adv-gamedetailpage-link'=>array('name'=>'游戏详情页跳转链接广告','url'=>'adv/ads/'),
                'adv-gamedetailpage-like'=>array('name'=>'游戏详情页猜你喜欢广告','url'=>'adv/ads/list/7'),
                'adv-startpage'=>array('name'=>'启动页广告','url'=>'adv/ads/list/5'),
                )          
            ),
        	'statistics'=>array('name'=>'统计','url'=>'statistics/rank/index','child_menu'=>array(
        		'credit-statistics'=>array('name'=>'游币','url'=>'statistics/rank/index'),
        		'user-credit-statistics'=>array('name'=>'用户游币','url'=>'statistics/usercredit/index'),
        		'forum-statistics'=>array('name'=>'论坛','url'=>'statistics/forum/index'),
        		'tuiguang-record'=>array('name'=>'推广统计', 'url'=>'statistics/tuiguang/index')
        		)
        	),
        	'xgame'=>array('name'=>'小游戏','url'=>'xgame/forum/index','child_menu'=>array(
        		'cradd-xgame'=>array('name'=>'添加','url'=>'xgame/forum/add'),
        		'credit-xgame'=>array('name'=>'查看','url'=>'xgame/forum/index'),
        		'bannerlist-xgame'=>array('name'=>'查看banner','url'=>'xgame/forum/banner-list'),
        		)
        	),
        )
    ), 
    'group_editor'=>array(
        'name'=>'编辑',
        'permission'=>array(),
        'menu'=>array(
            'system'=>array()
        )
    ), 
	'menu_key_match'=>array(
    	'system'=>'系统',
		'game'=>'游戏库',
		'forum'=>'微论坛',
		'user'=>'用户',
        'statistics'=>'统计',
		'comment'=>'评论',
		'activity'=>'活动',
		'shop'=>'商城',
		'giftbag'=>'礼包',
		'message'=>'消息推送',
		'feedback'=>'用户反馈',
		'adv'=>'广告'
    ),
	'monolog_channel'=>array(
		'system/setting'=>'网站设置',
		'system/admin'=>'管理员列表',
		'system/credit'=>'积分设置',
		'system/grade'=>'用户等级',
		'system/permission'=>'权限设置',
		'system/group'=>'权限组设置',
		'adv/credit'=>'游戏下载游币奖励',
		'forum/topic'=>'帖子管理',
		'comment/comments'=>'评论管理',
		'shop/goods'=>'商品管理',
		'user/users'=>'用户管理'
	),
	'game_types' => array(
		1=>'角色扮演',2=>'策略塔防',3=>'休闲益智',4=>'冒险解密',5=>'动作格斗',6=>'射击空战',
		7=>'音乐体育',8=>'桌游棋牌',9=>'儿童游戏',10=>'赛车竞速',11=>'模拟经营',12=>'网络游戏'
	)
);